/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv` (hash: 1e3db1be058bef800b022e9f83775f67)
interface __BaseEnv_CloudflareEnv {
	ATTACHMENTS: R2Bucket;
	EVENT_EVERY_DB: D1Database;
	ACCOUNTS_DB: D1Database;
	EMAIL: SendEmail;
	ASSETS: Fetcher;
	STATE_AUTHORITY_MODE: "cloudflare";
	IDENTITY_KEY_CURRENT_VERSION: "local-v1";
	IDENTITY_KEY_NEXT_VERSION: "";
	IDENTITY_KEY_ACTIVATES_AT: "";
	IDENTITY_KEY_SCHEDULE_DIGEST: "local-v1-no-rotation";
	PROVIDER_POLICY_VERSION: "owner-v1";
	PROVIDER_REQUEST_HMAC_CURRENT_VERSION: "c1-b-current-v1";
	PROVIDER_REQUEST_HMAC_PREVIOUS_VERSION: "";
	EMAIL_PROVIDER: "cloudflare";
	EMAIL_FROM: "Event Every <no-reply@mail.eventevery.com>";
	APP_ORIGIN: "https://eventevery.com";
	MCP_ORIGIN: "https://event-every-mcp.mannanteam.workers.dev";
	OPENROUTER_ADMIN_KEY: string;
	IDENTITY_DAY_POLICY: DurableObjectNamespace<import("./cloudflare/app-worker").IdentityDayPolicy>;
	RESOLVER_REQUEST_AUTHORITY: DurableObjectNamespace<import("./cloudflare/app-worker").ResolverRequestAuthority>;
	RESOLVER_DAILY_COUNTER: DurableObjectNamespace<import("./cloudflare/app-worker").DailyCounter>;
	OWNER_BUDGET_AUTHORITY: DurableObjectNamespace<import("./cloudflare/app-worker").OwnerBudgetAuthority>;
	PROVIDER_REQUEST_AUTHORITY: DurableObjectNamespace<import("./cloudflare/app-worker").ProviderRequestAuthority>;
	WORKER_SELF_REFERENCE: Service<typeof import("./cloudflare/app-worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./cloudflare/app-worker");
		durableNamespaces: "IdentityDayPolicy" | "ResolverRequestAuthority" | "DailyCounter" | "OwnerBudgetAuthority" | "ProviderRequestAuthority";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "STATE_AUTHORITY_MODE" | "IDENTITY_KEY_CURRENT_VERSION" | "IDENTITY_KEY_NEXT_VERSION" | "IDENTITY_KEY_ACTIVATES_AT" | "IDENTITY_KEY_SCHEDULE_DIGEST" | "PROVIDER_POLICY_VERSION" | "PROVIDER_REQUEST_HMAC_CURRENT_VERSION" | "PROVIDER_REQUEST_HMAC_PREVIOUS_VERSION" | "EMAIL_PROVIDER" | "EMAIL_FROM" | "APP_ORIGIN" | "MCP_ORIGIN" | "OPENROUTER_ADMIN_KEY">> {}
}
