/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv` (hash: e71d0195db16d136f1bccec486f71d17)
interface __BaseEnv_CloudflareEnv {
	EVENT_EVERY_DB: D1Database;
	ASSETS: Fetcher;
	C1_DEPLOYMENT_DISABLED: "1";
	STATE_AUTHORITY_MODE: "legacy";
	IDENTITY_KEY_CURRENT_VERSION: "local-v1";
	IDENTITY_KEY_NEXT_VERSION: "";
	IDENTITY_KEY_ACTIVATES_AT: "";
	IDENTITY_KEY_SCHEDULE_DIGEST: "local-v1-no-rotation";
	IDENTITY_HMAC_CURRENT: "";
	IDENTITY_HMAC_NEXT: "";
	RESOLVER_CAPABILITY_HMAC: "";
	WORKER_SELF_REFERENCE: Service<typeof import("./cloudflare/app-worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./cloudflare/app-worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "C1_DEPLOYMENT_DISABLED" | "STATE_AUTHORITY_MODE" | "IDENTITY_KEY_CURRENT_VERSION" | "IDENTITY_KEY_NEXT_VERSION" | "IDENTITY_KEY_ACTIVATES_AT" | "IDENTITY_KEY_SCHEDULE_DIGEST" | "IDENTITY_HMAC_CURRENT" | "IDENTITY_HMAC_NEXT" | "RESOLVER_CAPABILITY_HMAC">> {}
}
