/**
 * Host-supplied scan context.
 *
 * The vendored Scanner prompt forbids inventing a year, and the wire schema has
 * no way to carry a time without one: `floating` and `zoned` points both require
 * a complete date. Faced with "Tuesday, September 22 - 7:00pm" the model's only
 * legal moves are a `partial` point or a null start, and it takes both roughly
 * at random. Either way `missing_year` is a blocker and the event cannot export.
 *
 * Supplying today's date turns the year into a derivation rather than an
 * invention, which is the one thing the prompt actually prohibits. The weekday
 * rule matters more than it looks: a source naming a weekday pins the year on
 * its own, because a given month/day falls on a given weekday roughly once every
 * six years.
 *
 * This lives in `src/` rather than `vendor/`, which is a hash-locked artifact
 * regenerated by `bun run vendor:scanner` and would lose the edit.
 */

export type ScanContext = Readonly<{
  /** Instant the scan was admitted, as epoch milliseconds. */
  nowMs: number;
  /** IANA zone the reader is most likely in. */
  timeZone: string;
}>;

const FALLBACK_TIME_ZONE = 'UTC';

function isValidTimeZone(value: string): boolean {
  try {
    new Intl.DateTimeFormat('en-US', { timeZone: value });
    return true;
  } catch {
    return false;
  }
}

export function resolveScanTimeZone(candidate: string | null | undefined): string {
  if (typeof candidate !== 'string') return FALLBACK_TIME_ZONE;
  const trimmed = candidate.trim();
  if (trimmed.length === 0 || trimmed.length > 64) return FALLBACK_TIME_ZONE;
  return isValidTimeZone(trimmed) ? trimmed : FALLBACK_TIME_ZONE;
}

/** Calendar date and weekday of `nowMs` as read in `timeZone`. */
function localToday(context: ScanContext): Readonly<{ date: string; weekday: string }> {
  const parts = new Intl.DateTimeFormat('en-CA', {
    timeZone: context.timeZone,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    weekday: 'long',
  }).formatToParts(new Date(context.nowMs));
  const lookup = (type: Intl.DateTimeFormatPartTypes) =>
    parts.find((part) => part.type === type)?.value ?? '';
  return {
    date: `${lookup('year')}-${lookup('month')}-${lookup('day')}`,
    weekday: lookup('weekday'),
  };
}

export function buildScanContextMessage(context: ScanContext): string {
  const today = localToday(context);
  return [
    'Scan context supplied by the host, not by any source.',
    `The current date is ${today.date} (${today.weekday}). The reader time zone is ${context.timeZone}.`,
    'Resolving an omitted year against this context is derivation from supplied context, not invention.',
    'When a source states a month and day with no year, return the point with the year of the next',
    'occurrence on or after the current date, and prefer the year whose weekday matches a weekday named',
    'in the source. Never shift a month, day, or time to make a weekday match.',
    'Resolve relative dates - today, tomorrow, next Friday, this weekend - against the current date.',
    'A year that still cannot be derived leaves the point as kind "partial" with a null year.',
    'Never null a start that the source states. A partial point preserves the date; a null start loses it.',
    'A clock time written with the date is part of the start: return a point that carries that time,',
    'never a date-only point. A date-only point is only for a source that states no time at all.',
    'A stated end or closing time is the end point. A range like "7:00 - 8:30pm" is a start and an end.',
    'A time zone the source names - an IANA name such as America/New_York, an abbreviation such as ET,',
    'or "Time zone: ..." - makes the point zoned with that zone. Do not resolve times into the reader zone.',
    'The title is the name of the event itself, not the heading, app or section it appears under:',
    'in "Google Meet joining info" above an event called "Civic Signal", the title is "Civic Signal".',
    'This context names no event. Never emit a candidate for the current date alone.',
  ].join('\n');
}
