/**
 * Steer the model toward a timed point when the source states a time.
 *
 * The Scanner's wire schema describes a temporal point as a `oneOf` over four
 * kinds and says nothing about when each applies. Under strict schema decoding
 * the `date` kind is listed first, and measured 2026-09-15 that is what the
 * models return for "Friday March 13 2026 at 9:30am": a date-only point, the
 * time discarded, on every run of the text model. The host context message
 * saying otherwise did not move it; the schema did. With the branches
 * reordered and described, the same model returned 09:30 on every run.
 *
 * This touches only the schema the model sees. The completion is still parsed
 * by the Scanner's own Zod schema, which is order-independent, so nothing that
 * was valid before becomes invalid and nothing invalid becomes accepted. It
 * lives in `src/` because `vendor/` is regenerated by `bun run vendor:scanner`.
 */

const POINT_GUIDANCE: Readonly<Record<string, string>> = Object.freeze({
  floating: 'A calendar date with a clock time the source states, and no time zone stated by the source. Use this whenever the source gives a time and names no zone.',
  zoned: 'A calendar date with a clock time and a time zone the source itself names (an IANA name, an abbreviation such as ET, or a "Time zone:" line). The reader zone in the scan context is not a source zone.',
  partial: 'A date or time the source states only in part, such as a month and day with no derivable year.',
  date: 'A calendar date only. Use this only when the source states no clock time at all for the event.',
});

const POINT_ORDER: readonly string[] = Object.freeze(['floating', 'zoned', 'partial', 'date']);

type Branch = Readonly<{ properties?: Readonly<{ kind?: Readonly<{ const?: unknown }> }> }>;

function kindOf(branch: unknown): string | null {
  const value = (branch as Branch)?.properties?.kind?.const;
  return typeof value === 'string' ? value : null;
}

function isPointUnion(oneOf: unknown): oneOf is unknown[] {
  return Array.isArray(oneOf) && oneOf.some((branch) => {
    const kind = kindOf(branch);
    return kind !== null && POINT_ORDER.includes(kind);
  });
}

function guide(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(guide);
  if (!node || typeof node !== 'object') return node;
  const record = node as Record<string, unknown>;
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(record)) {
    if (key === 'oneOf' && isPointUnion(value)) {
      out.oneOf = [...value]
        .map((branch) => {
          const guidance = POINT_GUIDANCE[kindOf(branch) ?? ''];
          return guidance ? { ...(guide(branch) as Record<string, unknown>), description: guidance } : guide(branch);
        })
        .sort((a, b) => POINT_ORDER.indexOf(kindOf(a) ?? '') - POINT_ORDER.indexOf(kindOf(b) ?? ''));
      continue;
    }
    out[key] = guide(value);
  }
  return out;
}

/** Returns a copy of the provider request whose JSON schema carries the point guidance. */
export function withGuidedSchema<Request extends Readonly<Record<string, unknown>>>(request: Request): Request {
  const responseFormat = request.response_format as Readonly<{ json_schema?: Readonly<{ schema?: unknown }> }> | undefined;
  const schema = responseFormat?.json_schema?.schema;
  if (!schema || typeof schema !== 'object') return request;
  return {
    ...request,
    response_format: {
      ...responseFormat,
      json_schema: { ...responseFormat?.json_schema, schema: guide(schema) },
    },
  };
}
