import type { OpenRouterTransport } from '@event-every/scanner/openrouter';
import type { ProviderInvocation } from '@/platform/provider/transport';

/**
 * Drop the character offsets a model puts on its evidence citations.
 *
 * WHY, because deleting data a model produced needs a reason.
 *
 * The Scanner rejects a whole observation when any text evidence reports an
 * `endOffset` past the end of the source (wire-schema.js:117). Models get the
 * event right and still miscount that offset by a few characters, and the entire
 * extraction is discarded for it. Measured over 27 ground-truth inputs, that one
 * check accounted for 9 of 11 failures - 82% - and was the dominant cause of
 * /api/scan returning 502.
 *
 * Nothing is lost by dropping them. `toDurableScanReplay` projects every claim
 * through `projectClaim`, which sets `evidence: []`, and `DurableScanReplaySchema`
 * requires `evidence.length === 0`. The offsets are deleted one function later
 * and may not be stored at all - so the app was destroying good extractions to
 * enforce a contract it never consumes.
 *
 * Both offsets go to null together, which the wire schema explicitly allows
 * (`startOffset === null && endOffset === null` passes its refine) and which is
 * what image evidence is already required to use. Nulling only one would fail
 * the same refine.
 *
 * This stays here rather than in the vendored package: `vendor/` is generated by
 * `bun run vendor:scanner` and any edit there is lost on the next re-vendor. If
 * the Scanner ever learns to tolerate out-of-range offsets itself, delete this.
 */
function withoutEvidenceOffsets(body: unknown): unknown {
  const choice = (body as { choices?: { message?: { content?: unknown } }[] })?.choices?.[0];
  const content = choice?.message?.content;
  if (typeof content !== 'string' || content.length === 0) return body;

  let wire: unknown;
  try {
    wire = JSON.parse(content);
  } catch {
    // Not JSON. Leave it exactly as it came so the Scanner reports the real
    // problem rather than one introduced here.
    return body;
  }

  let touched = false;
  const strip = (node: unknown): void => {
    if (Array.isArray(node)) {
      for (const item of node) strip(item);
      return;
    }
    if (!node || typeof node !== 'object') return;
    const record = node as Record<string, unknown>;
    if ('startOffset' in record || 'endOffset' in record) {
      if (record.startOffset !== null || record.endOffset !== null) touched = true;
      record.startOffset = null;
      record.endOffset = null;
    }
    for (const value of Object.values(record)) strip(value);
  };
  strip(wire);
  if (!touched) return body;

  // Rebuilt rather than mutated in place: the caller's envelope is not ours.
  return {
    ...(body as Record<string, unknown>),
    choices: [
      { ...choice, message: { ...choice?.message, content: JSON.stringify(wire) } },
      ...((body as { choices?: unknown[] }).choices ?? []).slice(1),
    ],
  };
}

/** Adapts the vendored Scanner port to the coordinator's one permitted invocation. */
export function createEventEveryOpenRouterTransport(
  input: Readonly<{ invoke: ProviderInvocation; signal?: AbortSignal }>,
): OpenRouterTransport {
  return {
    async complete(request) {
      let result;
      try {
        result = await input.invoke(request);
      } catch {
        return { ok: false, failure: 'network', status: null, retryable: false };
      }
      if (result.status === 'success') return { ok: true, body: withoutEvidenceOffsets(result.value) };
      if (result.status === 'unknown') {
        return { ok: false, failure: 'network', status: null, retryable: false };
      }
      const status = result.providerStatus ?? null;
      return {
        ok: false,
        failure: 'http',
        status,
        retryable: status === 408 || status === 429 || (status !== null && status >= 500),
      };
    },
  };
}
