import type { OpenRouterTransport } from '@event-every/scanner/openrouter';
import type { ProviderInvocation } from '@/platform/provider/transport';
import { buildScanContextMessage, type ScanContext } from '@/server/scanner/scanContext';
import { withGuidedSchema } from '@/server/scanner/schemaGuidance';

/**
 * The Scanner builds `[system, user]`. The host context goes between them: after
 * the extraction contract, so it cannot be mistaken for it, and before the
 * source, so the model reads it as the frame rather than as content to extract.
 */
function withScanContext(
  request: Readonly<{ messages: readonly unknown[] }>,
  context: ScanContext | undefined,
): typeof request {
  if (!context) return request;
  const [system, ...rest] = request.messages;
  if (system === undefined) return request;
  return {
    ...request,
    messages: [system, { role: 'system', content: buildScanContextMessage(context) }, ...rest],
  };
}

/**
 * Drop the character offsets a model puts on its evidence citations.
 *
 * WHY, because deleting data a model produced needs a reason.
 *
 * The Scanner rejects a whole observation over an evidence citation it never
 * needs. For text it now tolerates an out-of-range offset itself (the library
 * fix that replaced the first version of this function on 2026-09-13). For
 * images it does not: image evidence must carry null offsets, and the vision
 * model cites `startOffset`/`endOffset` on nearly every image it reads. Measured
 * 2026-09-15 on a screenshot of a Meet invite: the model returned the correct
 * zoned 19:00-20:30 on every run and the observation was discarded on 6 of 7,
 * so the user saw "error scanning" for an extraction that was right.
 *
 * Nothing is lost by dropping them. `toDurableScanReplay` projects every claim
 * through `projectClaim`, which sets `evidence: []`, and `DurableScanReplaySchema`
 * requires `evidence.length === 0`. The offsets are deleted one function later
 * and may not be stored at all.
 *
 * Both offsets go to null together, which the wire schema explicitly allows and
 * which image evidence is required to use. Nulling only one fails its refine.
 *
 * This stays here rather than in the vendored package: `vendor/` is generated by
 * `bun run vendor:scanner` and any edit there is lost on the next re-vendor.
 * Removing it once before, on the strength of the text-only library fix, is
 * what broke image scans.
 */
function withoutEvidenceOffsets(body: unknown): unknown {
  const choice = (body as { choices?: { message?: { content?: unknown } }[] })?.choices?.[0];
  const content = choice?.message?.content;
  if (typeof content !== 'string' || content.length === 0) return body;

  let wire: unknown;
  try {
    wire = JSON.parse(content);
  } catch {
    // Not JSON. Leave it exactly as it came so the Scanner reports the real
    // problem rather than one introduced here.
    return body;
  }

  let touched = false;
  const strip = (node: unknown): void => {
    if (Array.isArray(node)) {
      for (const item of node) strip(item);
      return;
    }
    if (!node || typeof node !== 'object') return;
    const record = node as Record<string, unknown>;
    if ('startOffset' in record || 'endOffset' in record) {
      if (record.startOffset !== null || record.endOffset !== null) touched = true;
      record.startOffset = null;
      record.endOffset = null;
    }
    for (const value of Object.values(record)) strip(value);
  };
  strip(wire);
  if (!touched) return body;

  // Rebuilt rather than mutated in place: the caller's envelope is not ours.
  return {
    ...(body as Record<string, unknown>),
    choices: [
      { ...choice, message: { ...choice?.message, content: JSON.stringify(wire) } },
      ...((body as { choices?: unknown[] }).choices ?? []).slice(1),
    ],
  };
}

/** Adapts the vendored Scanner port to the coordinator's one permitted invocation. */
export function createEventEveryOpenRouterTransport(
  input: Readonly<{ invoke: ProviderInvocation; signal?: AbortSignal; context?: ScanContext }>,
): OpenRouterTransport {
  return {
    async complete(request) {
      let result;
      try {
        result = await input.invoke(withGuidedSchema(withScanContext(request, input.context)) as typeof request);
      } catch {
        return { ok: false, failure: 'network', status: null, retryable: false };
      }
      if (result.status === 'success') return { ok: true, body: withoutEvidenceOffsets(result.value) };
      if (result.status === 'unknown') {
        return { ok: false, failure: 'network', status: null, retryable: false };
      }
      const status = result.providerStatus ?? null;
      return {
        ok: false,
        failure: 'http',
        status,
        retryable: status === 408 || status === 429 || (status !== null && status >= 500),
      };
    },
  };
}
