import { z } from 'zod';
import { RecurrenceClaimSchema, TemporalClaimSchema, type IssueCode } from '@event-every/scanner';

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const bytes = (value: string) => new TextEncoder().encode(value).byteLength;
const invalid = (): never => { throw new Error('provider_invalid_response'); };
const bounded = (max: number) => z.string().refine((value) => bytes(value) <= max);
const field = ['sourceUid', 'title', 'description', 'location', 'url', 'temporal', 'recurrence', 'candidate', 'scan'] as const;
const codes = ['field_not_found', 'field_incomplete', 'field_ambiguous', 'field_conflicting', 'invalid_url', 'invalid_date', 'invalid_time', 'invalid_time_zone', 'invalid_duration', 'missing_start', 'missing_year', 'unknown_all_day', 'floating_time', 'dst_gap', 'dst_fold', 'offset_mismatch', 'end_before_start', 'end_duration_conflict', 'incompatible_temporal_kinds', 'invalid_recurrence', 'unsupported_recurrence', 'missing_export_uid', 'invalid_dtstamp', 'invalid_prodid', 'malformed_ics'] as const;
const issue = z.object({ code: z.enum(codes), field: z.enum(field) }).strict();
const source = z.object({ sourceId: z.string().regex(UUID), kind: z.enum(['text', 'image']), contentHandle: z.string().regex(UUID) }).strict();
const claim = <T extends z.ZodType>(value: T) => z.object({ value: value.nullable(), confidence: z.number().finite().min(0).max(1).nullable(), evidence: z.array(z.never()).length(0) }).strict();
const candidate = z.object({ candidateId: z.string().regex(UUID), sourceUid: z.null(), title: claim(bounded(512)), description: claim(bounded(16 * 1024)), location: claim(bounded(2 * 1024)), url: claim(bounded(2_048)), temporal: claim(TemporalClaimSchema), recurrence: claim(RecurrenceClaimSchema), issues: z.array(issue) }).strict().refine((value) => bytes(JSON.stringify(value)) <= 64 * 1024);
export const DurableScanReplaySchema = z.object({ source, candidates: z.array(candidate).max(50), issues: z.array(issue).max(200) }).strict().superRefine((value, context) => { if (value.candidates.reduce((count, item) => count + item.issues.length, value.issues.length) > 200) context.addIssue({ code: 'custom', message: 'too many issues' }); });
export const DurableSummaryReplaySchema = z.object({ summary: bounded(96).refine((value) => /^\p{Lu}\p{Ll}*(?:\p{Zs}+\p{Lu}\p{Ll}*){1,2}$/u.test(value)) }).strict();
export const DurableTimezoneReplaySchema = z.object({ timezone: bounded(255), confidence: z.number().finite().min(0).max(1) }).strict();

const COPY: Record<IssueCode, string> = { field_not_found: 'This field was not found.', field_incomplete: 'This field is incomplete.', field_ambiguous: 'This field is ambiguous.', field_conflicting: 'This field conflicts with another value.', invalid_url: 'The URL is invalid.', invalid_date: 'The date is invalid.', invalid_time: 'The time is invalid.', invalid_time_zone: 'The time zone is invalid.', invalid_duration: 'The duration is invalid.', missing_start: 'A start time is required.', missing_year: 'A year is required.', unknown_all_day: 'All-day status is unknown.', floating_time: 'The time has no time zone.', dst_gap: 'The time falls in a daylight-saving gap.', dst_fold: 'The time falls in a daylight-saving fold.', offset_mismatch: 'The offset does not match.', end_before_start: 'The end is before the start.', end_duration_conflict: 'The end conflicts with the duration.', incompatible_temporal_kinds: 'Temporal values are incompatible.', invalid_recurrence: 'The recurrence is invalid.', unsupported_recurrence: 'The recurrence is unsupported.', missing_export_uid: 'An export UID is required.', invalid_dtstamp: 'The timestamp is invalid.', invalid_prodid: 'The product ID is invalid.', malformed_ics: 'The calendar data is malformed.' };
const TRAITS: Record<IssueCode, Readonly<{ kind: string; severity: string }>> = { field_not_found: { kind: 'not_found', severity: 'warning' }, field_incomplete: { kind: 'incomplete', severity: 'blocker' }, field_ambiguous: { kind: 'ambiguous', severity: 'blocker' }, field_conflicting: { kind: 'conflicting', severity: 'blocker' }, invalid_url: { kind: 'invalid', severity: 'blocker' }, invalid_date: { kind: 'invalid', severity: 'blocker' }, invalid_time: { kind: 'invalid', severity: 'blocker' }, invalid_time_zone: { kind: 'invalid', severity: 'blocker' }, invalid_duration: { kind: 'invalid', severity: 'blocker' }, missing_start: { kind: 'incomplete', severity: 'blocker' }, missing_year: { kind: 'incomplete', severity: 'blocker' }, unknown_all_day: { kind: 'ambiguous', severity: 'blocker' }, floating_time: { kind: 'ambiguous', severity: 'warning' }, dst_gap: { kind: 'ambiguous', severity: 'blocker' }, dst_fold: { kind: 'ambiguous', severity: 'blocker' }, offset_mismatch: { kind: 'conflicting', severity: 'blocker' }, end_before_start: { kind: 'conflicting', severity: 'blocker' }, end_duration_conflict: { kind: 'conflicting', severity: 'blocker' }, incompatible_temporal_kinds: { kind: 'conflicting', severity: 'blocker' }, invalid_recurrence: { kind: 'invalid', severity: 'blocker' }, unsupported_recurrence: { kind: 'unsupported', severity: 'blocker' }, missing_export_uid: { kind: 'incomplete', severity: 'blocker' }, invalid_dtstamp: { kind: 'invalid', severity: 'blocker' }, invalid_prodid: { kind: 'invalid', severity: 'blocker' }, malformed_ics: { kind: 'invalid', severity: 'blocker' } };
const rawClaim = z.object({ value: z.unknown().nullable(), confidence: z.number().finite().min(0).max(1).nullable(), evidence: z.array(z.unknown()) }).strict();
const projectClaim = (value: unknown) => { const parsed = rawClaim.safeParse(value); if (!parsed.success || !parsed.data) return invalid(); return { value: parsed.data.value, confidence: parsed.data.confidence, evidence: [] as never[] }; };
const projectIssue = (value: unknown) => { const parsed = issue.passthrough().safeParse(value); if (!parsed.success || !parsed.data) return invalid(); return { code: parsed.data.code, field: parsed.data.field }; };
export function toDurableScanReplay(input: unknown): z.infer<typeof DurableScanReplaySchema> {
  if (!input || typeof input !== 'object' || Array.isArray(input)) return invalid(); const raw = input as Record<string, unknown>;
  if (!Array.isArray(raw.candidates) || !Array.isArray(raw.issues)) return invalid();
  const candidates = raw.candidates.map((item) => { if (!item || typeof item !== 'object' || Array.isArray(item)) return invalid(); const value = item as Record<string, unknown>; if (!Array.isArray(value.issues)) return invalid(); return { candidateId: value.candidateId, sourceUid: null, title: projectClaim(value.title), description: projectClaim(value.description), location: projectClaim(value.location), url: projectClaim(value.url), temporal: projectClaim(value.temporal), recurrence: projectClaim(value.recurrence), issues: value.issues.map(projectIssue) }; });
  const parsed = DurableScanReplaySchema.safeParse({ source: raw.source, candidates, issues: raw.issues.map(projectIssue) }); if (!parsed.success || !parsed.data) return invalid(); return parsed.data;
}
const materializeIssue = (value: z.infer<typeof issue>) => ({ ...value, ...TRAITS[value.code], message: COPY[value.code], evidence: [] });
export function materializeScanReplay(replay: z.infer<typeof DurableScanReplaySchema>) { const parsed = DurableScanReplaySchema.safeParse(replay); if (!parsed.success || !parsed.data) return invalid(); return { source: parsed.data.source, candidates: parsed.data.candidates.map((item) => ({ ...item, issues: item.issues.map(materializeIssue) })), issues: parsed.data.issues.map(materializeIssue) }; }
export function toDurableSummaryReplay(summary: unknown): z.infer<typeof DurableSummaryReplaySchema> { const parsed = DurableSummaryReplaySchema.safeParse({ summary }); if (!parsed.success || !parsed.data) return invalid(); return parsed.data; }
export function toDurableTimezoneReplay(input: unknown): z.infer<typeof DurableTimezoneReplaySchema> { const parsed = DurableTimezoneReplaySchema.safeParse(input); if (!parsed.success || !parsed.data) return invalid(); try { new Intl.DateTimeFormat('en-US', { timeZone: parsed.data.timezone }); } catch { return invalid(); } return parsed.data; }
