/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/legacy-keepalive-wrangler.jsonc --include-runtime=false --env-interface=LegacyKeepAliveEnv cloudflare/legacy-keepalive-configuration.d.ts` (hash: 324977619f434a1a6912e5dd725ead5a)
interface __BaseEnv_LegacyKeepAliveEnv {
	KEEPALIVE_DEPLOYMENT_DISABLED: "1";
	STATE_AUTHORITY_MODE: "legacy";
	KV_REST_API_URL: "";
	KV_REST_API_TOKEN: "";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_LegacyKeepAliveEnv {}
}
interface LegacyKeepAliveEnv extends __BaseEnv_LegacyKeepAliveEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "KEEPALIVE_DEPLOYMENT_DISABLED" | "STATE_AUTHORITY_MODE" | "KV_REST_API_URL" | "KV_REST_API_TOKEN">> {}
}
