import { createHash, randomBytes } from 'node:crypto';
import { once } from 'node:events';
import { existsSync, readFileSync, rmSync } from 'node:fs';
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import net from 'node:net';
import path from 'node:path';
import { Readable } from 'node:stream';
import tls from 'node:tls';
import { fileURLToPath } from 'node:url';
// @ts-expect-error Node strip-types requires the explicit local TypeScript extension.
import { assertNoWranglerLocalFiles, createCloudflareChildEnvironment, CREDENTIAL_NAME, installCloudflareProcessBoundary, type C1AEnvironment } from './run-c1-a-cloudflare.ts';

const PORT = 8788;
const MAX_CHILD_OUTPUT = 64 * 1024;
const STARTUP_TIMEOUT_MS = 30_000;
const PLAYWRIGHT_TIMEOUT_MS = 180_000;
const TERMINATION_GRACE_MS = 2_000;
const INTERNAL_MODE = '--internal-harness';
const INTERNAL_TOKEN_ENV = 'C1_A_WORKER_E2E_INTERNAL_TOKEN';
const INJECTION_CONTROLS = ['NODE_OPTIONS', 'BUN_OPTIONS', 'NODE_PATH', 'NODE_REPL_EXTERNAL_MODULE', 'LD_PRELOAD', 'DYLD_INSERT_LIBRARIES', 'DYLD_LIBRARY_PATH', 'HTTP_PROXY', 'HTTPS_PROXY', 'ALL_PROXY', 'NO_PROXY'] as const;
export const C1_A_WORKER_E2E_READY = 'C1_A_WORKER_E2E_READY';
const PLAYWRIGHT_TITLES = ['community exhaustion exposes no pattern or admin bypass', 'corrupt Scanner review storage recovers and persists the next scan', 'URL-only scan waits through resolver rollover and busy responses then succeeds'] as const;
const AUTHORED_INPUTS = ['open-next.config.ts', 'wrangler.jsonc', 'next.config.js', 'playwright.c1-a.config.ts', 'vitest.config.workers.ts'] as const;
const MODULE_DIR = (import.meta as ImportMeta & { dirname?: string }).dirname ?? path.dirname(fileURLToPath(import.meta.url));

export const C1_A_WORKER_E2E_STATES = ['preflight', 'process-boundary-installed', 'build', 'harness-child-started', 'harness-ready', 'http-ready', 'playwright-started', 'playwright-settled', 'playwright-stopped', 'harness-child-stopped', 'port-closed', 'outputs-removed'] as const;
export type C1AWorkerE2EState = typeof C1_A_WORKER_E2E_STATES[number];
export const C1_A_HARNESS_VARS = { IDENTITY_HMAC_CURRENT: 'synthetic-c1-a-identity-key', RESOLVER_CAPABILITY_HMAC: 'synthetic-c1-a-capability-key', OPENROUTER_COMMUNITY_KEY: 'synthetic-c1-a-never-sent' } as const;

type ParsedArgs = Readonly<{ project?: 'chromium' | 'webkit'; grep?: typeof PLAYWRIGHT_TITLES[number] }>;
type Harness = Readonly<{ listen(): Promise<unknown>; close(): Promise<void>; fetch(input: string | URL, init?: RequestInit): Promise<Response> }>;
type EgressGuard = Readonly<{ assertOutboundCanary(): void; close(): void }>;
export type C1AWorkerE2EChild = Readonly<{ exited: Promise<number>; stdout: ReadableStream<Uint8Array> | number | undefined; stderr: ReadableStream<Uint8Array> | number | undefined; kill(signal: 'SIGTERM' | 'SIGKILL'): unknown }>;
type OutputPaths = Readonly<{ openNext: string; wrangler: string; results: string; report: string }>;
type SignalName = 'SIGINT' | 'SIGTERM' | 'SIGHUP';
export type HarnessReadiness = Readonly<{ ready: Promise<void>; drained: Promise<string> }>;

export type C1AWorkerE2ESeams = Readonly<{
  randomSuffix(): string; randomToken(): string; assertNoWranglerLocalFiles(root: string): void; probePortFree(): Promise<void>; exists(file: string): boolean; hash(file: string): string; installCloudflareProcessBoundary(root: string): void; createChildEnvironment(root: string, suffix: string): C1AEnvironment;
  build(root: string, env: C1AEnvironment, signal: AbortSignal): Promise<void>; startHarnessChild(root: string, env: C1AEnvironment, token: string): Promise<C1AWorkerE2EChild>; startHarnessReadiness(child: C1AWorkerE2EChild, env: C1AEnvironment, signal: AbortSignal): HarnessReadiness; startupDeadline(): Promise<void>; playwrightDeadline(): Promise<void>;
  startPlaywright(root: string, env: C1AEnvironment, argv: readonly string[]): Promise<C1AWorkerE2EChild>; stopChild(child: C1AWorkerE2EChild, label: string): Promise<void>; assertPortClosed(): Promise<void>; removeOwned(paths: OutputPaths): void; subscribeSignals(listener: (signal: SignalName) => void): () => void;
}>;

function fail(message: string): never { throw new Error(`c1-a worker e2e: ${message}`); }
function asFailure(error: unknown): Error { return error instanceof Error && error.message.startsWith('c1-a worker e2e:') ? error : new Error('c1-a worker e2e: failed'); }
async function guarded<T>(label: string, action: () => Promise<T> | T): Promise<T> { try { return await action(); } catch (error) { if (error instanceof Error && error.message.startsWith('c1-a worker e2e:')) throw error; fail(`${label} failed`); } }
function outputPaths(root: string, suffix: string): OutputPaths { return { openNext: path.join(root, '.open-next'), wrangler: path.join(root, '.wrangler'), results: path.join(root, `test-results-c1-a-${suffix}`), report: path.join(root, `playwright-report-c1-a-${suffix}`) }; }
function hash(file: string): string { return createHash('sha256').update(readFileSync(file)).digest('hex'); }
export function createC1AWorkerE2EEnvironment(source: C1AEnvironment, root: string, suffix: string): C1AEnvironment { return { ...createCloudflareChildEnvironment(source, root), C1_A_OUTPUT_SUFFIX: suffix }; }
function childEnvironment(root: string, suffix: string): C1AEnvironment { return createC1AWorkerE2EEnvironment(process.env, root, suffix); }

export function createHarnessChildEnvironment(source: C1AEnvironment, root: string, token: string): C1AEnvironment { if (!/^[a-f0-9]{64}$/.test(token)) fail('internal invocation'); const env = { ...createCloudflareChildEnvironment(source, root) }; for (const name of Object.keys(env)) if (INJECTION_CONTROLS.some((control) => control.toLowerCase() === name.toLowerCase())) delete env[name]; for (const name of INJECTION_CONTROLS) { delete env[name]; delete env[name.toLowerCase()]; } env[INTERNAL_TOKEN_ENV] = token; return env; }
function redactionNeedles(env: C1AEnvironment): string[] { const needles: string[] = []; for (const [name, value] of [...Object.entries(env), ...Object.entries(C1_A_HARNESS_VARS)]) { if (CREDENTIAL_NAME.test(name)) needles.push(name); if (value) needles.push(value); } return [...new Set(needles)].sort((left, right) => right.length - left.length); }
function redactBounded(value: string, env: C1AEnvironment): string { let result = value.slice(0, MAX_CHILD_OUTPUT); for (const needle of redactionNeedles(env)) result = result.replaceAll(needle, '[redacted]'); return result.slice(0, MAX_CHILD_OUTPUT); }
export async function drainChildOutput(output: ReadableStream<Uint8Array> | number | undefined, env: C1AEnvironment): Promise<string> { if (!output || typeof output === 'number') return ''; const reader = output.getReader(); const decoder = new TextDecoder(); const needles = redactionNeedles(env); const longest = Math.max(1, ...needles.map((value) => value.length)); let captured = ''; let pending = ''; const consume = (final = false): void => { const limit = final ? pending.length : Math.max(0, pending.length - longest + 1); let index = 0; while (index < limit) { const match = needles.find((needle) => pending.startsWith(needle, index)); const value = match ? '[redacted]' : pending[index]; if (captured.length < MAX_CHILD_OUTPUT) captured += value.slice(0, MAX_CHILD_OUTPUT - captured.length); index += match?.length ?? 1; } pending = pending.slice(index); }; try { for (;;) { const { done, value } = await reader.read(); if (done) break; pending += decoder.decode(value, { stream: true }); consume(); } pending += decoder.decode(); consume(true); return captured; } finally { reader.releaseLock(); } }

export function parseC1AWorkerE2EArgs(argv: readonly string[]): ParsedArgs { const parsed: { project?: 'chromium' | 'webkit'; grep?: typeof PLAYWRIGHT_TITLES[number] } = {}; for (let index = 0; index < argv.length; index += 1) { const value = argv[index]; if (value.startsWith('--project=')) { const project = value.slice('--project='.length); if ((project !== 'chromium' && project !== 'webkit') || parsed.project) fail('arguments'); parsed.project = project; } else if (value === '--grep') { const grep = argv[++index]; if (!grep || !PLAYWRIGHT_TITLES.includes(grep as typeof PLAYWRIGHT_TITLES[number]) || parsed.grep) fail('arguments'); parsed.grep = grep as typeof PLAYWRIGHT_TITLES[number]; } else fail('arguments'); } return parsed; }
export function assertInternalHarnessInvocation(argv: readonly string[], env: C1AEnvironment, nodeVersion: string): void { const token = argv[1]; if (argv.length !== 2 || argv[0] !== INTERNAL_MODE || !/^[a-f0-9]{64}$/.test(token ?? '') || env[INTERNAL_TOKEN_ENV] !== token || Number(nodeVersion.split('.')[0]) < 22) fail('internal invocation'); }
export function harnessChildInvocation(root: string): readonly string[] { return ['node', '--no-warnings', '--experimental-strip-types', path.join(root, 'scripts', 'run-c1-a-worker-e2e.ts'), INTERNAL_MODE]; }
export function nodeHarnessChildInvocation(root: string, token: string): readonly string[] { return [...harnessChildInvocation(root), token]; }

async function probePortFree(): Promise<void> { const server = net.createServer(); try { server.listen(PORT, '127.0.0.1'); await once(server, 'listening'); } catch { fail('port 8788 unavailable'); } finally { if (server.listening) await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); } }
async function superviseBunChild(argv: readonly string[], root: string, env: C1AEnvironment, label: string, signal: AbortSignal): Promise<void> { let child: ReturnType<typeof Bun.spawn>; try { child = Bun.spawn([...argv], { cwd: root, env, stdout: 'pipe', stderr: 'pipe' }); } catch { fail(`${label} start failed`); } let timer: ReturnType<typeof setTimeout> | undefined; const abort = () => { child.kill('SIGTERM'); timer = setTimeout(() => child.kill('SIGKILL'), TERMINATION_GRACE_MS); }; signal.addEventListener('abort', abort, { once: true }); const output = Promise.all([drainChildOutput(child.stdout, env), drainChildOutput(child.stderr, env)]); try { const [code] = await Promise.all([child.exited, output]); if (code !== 0) fail(`${label} failed`); } finally { signal.removeEventListener('abort', abort); if (timer) clearTimeout(timer); await output.catch(() => undefined); } }
async function build(root: string, env: C1AEnvironment, signal: AbortSignal): Promise<void> { await superviseBunChild(['node', 'node_modules/@opennextjs/cloudflare/dist/cli/index.js', 'build'], root, env, 'build', signal); if (!existsSync(path.join(root, '.open-next', 'worker.js'))) fail('missing .open-next/worker.js'); }
async function startHarnessChild(root: string, parentEnv: C1AEnvironment, token: string): Promise<C1AWorkerE2EChild> { const env = createHarnessChildEnvironment(parentEnv, root, token); let child: ReturnType<typeof Bun.spawn>; try { child = Bun.spawn([...nodeHarnessChildInvocation(root, token)], { cwd: root, env, stdout: 'pipe', stderr: 'pipe' }); } catch { fail('harness child start failed'); } return { exited: child.exited, stdout: child.stdout, stderr: child.stderr, kill: (signal) => child.kill(signal) }; }

export function awaitHarnessChildReady(child: C1AWorkerE2EChild, env: C1AEnvironment, signal: AbortSignal): HarnessReadiness { if (!child.stdout || typeof child.stdout === 'number') { const rejected = Promise.reject(new Error('c1-a worker e2e: harness child readiness')); void rejected.catch(() => undefined); return { ready: rejected, drained: rejected.then(() => '') }; } const reader = child.stdout.getReader(); const expected = `${C1_A_WORKER_E2E_READY}\n`; let resolveReady!: () => void; let rejectReady!: (error: Error) => void; const ready = new Promise<void>((resolve, reject) => { resolveReady = resolve; rejectReady = reject; }); void ready.catch(() => undefined); let framed = ''; let accepted = false; let invalid = false; const abort = () => rejectReady(new Error('c1-a worker e2e: aborted')); signal.addEventListener('abort', abort, { once: true }); const drained = (async () => { let output = ''; const decoder = new TextDecoder(); try { for (;;) { const { done, value } = await reader.read(); if (done) break; const text = decoder.decode(value, { stream: true }); if (!accepted) { framed += text; if (expected.startsWith(framed)) { if (framed === expected) { accepted = true; resolveReady(); } } else { invalid = true; rejectReady(new Error('c1-a worker e2e: harness child readiness')); } } else if (text) invalid = true; if (output.length < MAX_CHILD_OUTPUT) output += text.slice(0, MAX_CHILD_OUTPUT - output.length); } output += decoder.decode(); if (!accepted) rejectReady(new Error('c1-a worker e2e: harness child readiness')); if (invalid) throw new Error('c1-a worker e2e: harness child stdout'); return redactBounded(output, env); } finally { signal.removeEventListener('abort', abort); reader.releaseLock(); } })(); void drained.catch(() => undefined); return { ready, drained }; }

function isLoopback(url: string): boolean { const host = new URL(url).hostname; return ['127.0.0.1', 'localhost', '::1', '[::1]'].includes(host); }
function isLoopbackSocketArgs(args: readonly unknown[]): boolean { const first = args[0]; const host = typeof first === 'number' ? args[1] : first && typeof first === 'object' ? (first as { hostname?: unknown; host?: unknown }).hostname ?? (first as { host?: unknown }).host : undefined; return typeof host === 'string' && ['127.0.0.1', 'localhost', '::1', '[::1]'].includes(host.toLowerCase()); }
export async function startEgressGuard(): Promise<EgressGuard> { const { setupServer } = await import('msw/node'); const { http, passthrough } = await import('msw'); const observed: Array<{ method: string; url: string }> = []; const originalNetConnect = net.connect; const originalNetCreateConnection = net.createConnection; const originalTlsConnect = tls.connect; const guardSocket = <T extends (...args: never[]) => unknown>(original: T): T => function guardedSocket(this: unknown, ...args: never[]) { if (!isLoopbackSocketArgs(args)) fail('non-loopback socket'); return original.apply(this, args); } as T; net.connect = guardSocket(net.connect); net.createConnection = guardSocket(net.createConnection); tls.connect = guardSocket(tls.connect); const server = setupServer(http.all(/^https?:\/\/(?:localhost|127(?:\.\d{1,3}){3}|\[::1\])(?::\d+)?(?:\/|$)/, ({ request }) => { if (!isLoopback(request.url)) fail('non-loopback egress'); return passthrough(); })); server.events.on('request:unhandled', ({ request }) => observed.push({ method: request.method, url: request.url })); try { server.listen({ onUnhandledRequest: 'error' }); } catch (error) { net.connect = originalNetConnect; net.createConnection = originalNetCreateConnection; tls.connect = originalTlsConnect; throw error; } return { assertOutboundCanary: () => { if (observed.length !== 1 || observed[0]?.method !== 'POST' || observed[0]?.url !== 'https://openrouter.ai/api/v1/chat/completions') fail('outbound canary target'); }, close: () => { net.connect = originalNetConnect; net.createConnection = originalNetCreateConnection; tls.connect = originalTlsConnect; server.close(); } }; }
export async function runOutboundCanary(harness: Harness, guard: EgressGuard): Promise<void> { const response = await harness.fetch('http://127.0.0.1:8788/api/scan', { method: 'POST', headers: { 'content-type': 'application/json', origin: 'http://127.0.0.1:8788', 'cf-connecting-ip': '203.0.113.10', 'X-Event-Every-Request-Id': '018f47a0-7b5c-7cc4-9a34-123456789abc' }, body: JSON.stringify({ kind: 'text', text: 'C1-A outbound canary' }) }); let body: unknown; try { body = await response.json(); } catch { fail('outbound canary response'); } if (response.status !== 502 || !body || typeof body !== 'object' || (body as { code?: unknown }).code !== 'scan_provider_failed') fail('outbound canary response'); guard.assertOutboundCanary(); }

export type BridgeRequest = Readonly<{ input: string; init: RequestInit }>;
export function requestFromNode(req: IncomingMessage): BridgeRequest { const headers = new Headers(); for (const [name, value] of Object.entries(req.headers)) if (value !== undefined) headers.set(name, Array.isArray(value) ? value.join(', ') : value); const method = req.method || 'GET'; const init: RequestInit = { method, headers }; if (method !== 'GET' && method !== 'HEAD') Object.assign(init, { body: Readable.toWeb(req) as unknown as ReadableStream, duplex: 'half' }); return { input: `http://127.0.0.1:${PORT}${req.url || '/'}`, init }; }
function streamResponse(response: Response, output: ServerResponse): void { output.statusCode = response.status; response.headers.forEach((value, name) => output.setHeader(name, value)); if (!response.body) return void output.end(); void (async () => { const reader = response.body!.getReader(); try { for (;;) { const { done, value } = await reader.read(); if (done) break; if (!output.write(value)) await once(output, 'drain'); } output.end(); } finally { reader.releaseLock(); } })().catch(() => output.destroy()); }
function bridgeFailure(output: ServerResponse): void { output.statusCode = 502; output.setHeader('content-type', 'application/json; charset=utf-8'); output.end(JSON.stringify({ error: 'Worker bridge dispatch failed.', code: 'worker_bridge_dispatch_failed' })); }
export async function dispatchBridgeRequest(harness: Harness, request: IncomingMessage, output: ServerResponse, convert: (request: IncomingMessage) => BridgeRequest = requestFromNode): Promise<void> { try { const { input, init } = convert(request); streamResponse(await harness.fetch(input, init), output); } catch { bridgeFailure(output); } }
async function startBridge(harness: Harness): Promise<{ close(): Promise<void> }> { const server = createServer((req, res) => void dispatchBridgeRequest(harness, req, res)); server.listen(PORT, '127.0.0.1'); await once(server, 'listening'); return { close: () => new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())) }; }
function playwrightArgv(parsed: ParsedArgs): string[] { const argv = ['node', 'node_modules/@playwright/test/cli.js', 'test', '--config', 'playwright.c1-a.config.ts']; if (parsed.project) argv.push(`--project=${parsed.project}`); if (parsed.grep) argv.push('--grep', parsed.grep); return argv; }
async function startPlaywright(root: string, env: C1AEnvironment, argv: readonly string[]): Promise<C1AWorkerE2EChild> { let child: ReturnType<typeof Bun.spawn>; try { child = Bun.spawn([...argv], { cwd: root, env, stdout: 'pipe', stderr: 'pipe' }); } catch { fail('playwright start failed'); } return { exited: child.exited, stdout: child.stdout, stderr: child.stderr, kill: (signal) => child.kill(signal) }; }
export async function stopChild(child: C1AWorkerE2EChild, label: string, sleep: (ms: number) => Promise<unknown> = detachedDelay): Promise<void> { const completion = child.exited.then(() => true, () => true); child.kill('SIGTERM'); if (await Promise.race([completion, sleep(TERMINATION_GRACE_MS).then(() => false)])) return; child.kill('SIGKILL'); if (!await Promise.race([completion, sleep(TERMINATION_GRACE_MS).then(() => false)])) fail(`${label} did not terminate`); }
function removeOwned(paths: OutputPaths): void { for (const target of Object.values(paths)) if (existsSync(target)) rmSync(target, { recursive: true, force: false }); }
function subscribeSignals(listener: (signal: SignalName) => void): () => void { const handlers = new Map<SignalName, () => void>(); for (const signal of ['SIGINT', 'SIGTERM', 'SIGHUP'] as const) { const handler = () => listener(signal); handlers.set(signal, handler); process.once(signal, handler); } return () => { for (const [signal, handler] of handlers) process.removeListener(signal, handler); }; }
export function detachedDelay(ms: number, schedule: typeof setTimeout = setTimeout): Promise<void> { return new Promise((resolve) => { const timer = schedule(resolve, ms); timer.unref?.(); }); }
export async function assertBridgeRootSmoke(fetchLoopback: (input: string, init: RequestInit) => Promise<Response> = fetch, signal?: AbortSignal): Promise<void> { if (signal?.aborted) fail('bridge root smoke'); const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 5_000); timeout.unref?.(); const abort = () => controller.abort(); signal?.addEventListener('abort', abort, { once: true }); try { const response = await fetchLoopback(`http://127.0.0.1:${PORT}/`, { method: 'GET', signal: controller.signal }); try { if (controller.signal.aborted || response.status !== 200) fail('bridge root smoke'); } finally { await response.body?.cancel().catch(() => undefined); } } catch (error) { if (error instanceof Error && error.message === 'c1-a worker e2e: bridge root smoke') throw error; fail('bridge root smoke'); } finally { clearTimeout(timeout); signal?.removeEventListener('abort', abort); } }
export function createInternalHarnessLifecycle(): Readonly<{ signal: AbortSignal; stopped: Promise<void>; terminate(): void }> { const controller = new AbortController(); let resolveStopped!: () => void; const stopped = new Promise<void>((resolve) => { resolveStopped = resolve; }); let terminated = false; return { signal: controller.signal, stopped, terminate: () => { if (terminated) return; terminated = true; controller.abort(); resolveStopped(); } }; }
export async function emitReadyAfterBridgeSmoke(smoke: (signal: AbortSignal) => Promise<void>, emit: () => void, signal?: AbortSignal): Promise<void> { if (signal?.aborted) fail('bridge root smoke'); await smoke(signal ?? new AbortController().signal); if (signal?.aborted) fail('bridge root smoke'); emit(); }

const DEFAULT_SEAMS: C1AWorkerE2ESeams = { randomSuffix: () => randomBytes(6).toString('hex'), randomToken: () => randomBytes(32).toString('hex'), assertNoWranglerLocalFiles, probePortFree, exists: existsSync, hash, installCloudflareProcessBoundary, createChildEnvironment: childEnvironment, build, startHarnessChild, startHarnessReadiness: awaitHarnessChildReady, startupDeadline: () => detachedDelay(STARTUP_TIMEOUT_MS), playwrightDeadline: () => detachedDelay(PLAYWRIGHT_TIMEOUT_MS), startPlaywright, stopChild, assertPortClosed: probePortFree, removeOwned, subscribeSignals };

export async function runC1AWorkerE2E(argv: readonly string[] = [], root = path.resolve(MODULE_DIR, '..'), seams: C1AWorkerE2ESeams = DEFAULT_SEAMS): Promise<readonly C1AWorkerE2EState[]> {
  const parsed = parseC1AWorkerE2EArgs(argv); const states: C1AWorkerE2EState[] = []; const suffix = seams.randomSuffix(); const token = seams.randomToken(); if (!/^[a-f0-9]{12}$/.test(suffix) || !/^[a-f0-9]{64}$/.test(token)) fail('invalid invocation token'); const paths = outputPaths(root, suffix); const authored = AUTHORED_INPUTS.map((file) => path.join(root, file)); const hashes = new Map<string, string>(); let harnessChild: C1AWorkerE2EChild | undefined; let playwright: C1AWorkerE2EChild | undefined; let aborted: SignalName | undefined; let cancellation: Error | undefined; let rejectAbort!: (reason: Error) => void; const abortController = new AbortController(); const abort = new Promise<never>((_resolve, reject) => { rejectAbort = reject; }); void abort.catch(() => undefined); const lateAcquisitions: Promise<void>[] = []; const lateCleanupErrors: Error[] = []; const drainErrors: Error[] = []; const drains: Promise<void>[] = [];
  const cancel = (reason: Error): void => { if (!cancellation) { cancellation = reason; abortController.abort(); rejectAbort(reason); } }; const unsubscribe = seams.subscribeSignals((signal) => { if (!aborted) { aborted = signal; cancel(new Error(`c1-a worker e2e: aborted (${signal})`)); } }); const interruptible = <T>(work: Promise<T>): Promise<T> => cancellation ? Promise.reject(cancellation) : Promise.race([work, abort]); const trackDrain = (label: string, drain: Promise<unknown>): void => { const observed = drain.then(() => undefined, () => { drainErrors.push(new Error(`c1-a worker e2e: ${label} drain failed`)); }); drains.push(observed); };
  const acquire = async <T>(label: string, work: Promise<T>, cleanup: (value: T) => Promise<void>): Promise<T> => { let handedOff = false; const watched = work.then(async (value) => { if (cancellation && !handedOff) { try { await cleanup(value); } catch { lateCleanupErrors.push(new Error(`c1-a worker e2e: late ${label} cleanup failed`)); } throw cancellation; } return value; }); lateAcquisitions.push(watched.then(() => undefined, () => undefined)); const value = await interruptible(watched); handedOff = true; return value; };
  let primary: Error | undefined; let ownsOutputs = false; let startupFinished = false; let playwrightFinished = false;
  try { await guarded('local-vars preflight', () => seams.assertNoWranglerLocalFiles(root)); await interruptible(guarded('port preflight', () => seams.probePortFree())); if (Object.values(paths).some(seams.exists)) fail('owned output collision'); ownsOutputs = true; for (const file of authored) hashes.set(file, await guarded('authored-input preflight', () => seams.hash(file))); states.push('preflight'); await guarded('process boundary', () => seams.installCloudflareProcessBoundary(root)); states.push('process-boundary-installed'); const env = await guarded('child environment', () => seams.createChildEnvironment(root, suffix)); const buildWork = guarded('build', () => seams.build(root, env, abortController.signal)); lateAcquisitions.push(buildWork.then(() => undefined, () => undefined)); await interruptible(buildWork); states.push('build');
    const startup = seams.startupDeadline().then(() => { if (!startupFinished) cancel(new Error('c1-a worker e2e: harness startup timeout')); }); void startup.catch(() => undefined); harnessChild = await acquire('harness child', guarded('harness child start', () => seams.startHarnessChild(root, env, token)), (value) => seams.stopChild(value, 'harness child')); states.push('harness-child-started'); const readiness = seams.startHarnessReadiness(harnessChild, env, abortController.signal); trackDrain('harness stdout', readiness.drained); trackDrain('harness stderr', drainChildOutput(harnessChild.stderr, createHarnessChildEnvironment(env, root, token))); await interruptible(guarded('harness readiness', () => readiness.ready)); startupFinished = true; states.push('harness-ready'); states.push('http-ready');
    playwright = await acquire('playwright', guarded('playwright start', () => seams.startPlaywright(root, env, playwrightArgv(parsed))), (value) => seams.stopChild(value, 'playwright')); trackDrain('playwright stdout', drainChildOutput(playwright.stdout, env)); trackDrain('playwright stderr', drainChildOutput(playwright.stderr, env)); states.push('playwright-started'); const deadline = seams.playwrightDeadline().then(() => { if (!playwrightFinished) cancel(new Error('c1-a worker e2e: playwright timeout')); }); void deadline.catch(() => undefined); const outcome = await interruptible(Promise.race([playwright.exited.then((code) => ({ kind: 'playwright' as const, code })), harnessChild.exited.then((code) => ({ kind: 'harness' as const, code }))])); playwrightFinished = true; if (outcome.kind === 'harness') fail('harness child exited'); if (outcome.code !== 0) fail('playwright failed'); states.push('playwright-settled');
  } catch (error) { primary = asFailure(error); } finally { startupFinished = true; playwrightFinished = true; const cleanupErrors: Error[] = []; if (playwright) try { await seams.stopChild(playwright, 'playwright'); states.push('playwright-stopped'); } catch { cleanupErrors.push(new Error('c1-a worker e2e: playwright cleanup failed')); } if (harnessChild) try { await seams.stopChild(harnessChild, 'harness child'); states.push('harness-child-stopped'); } catch { cleanupErrors.push(new Error('c1-a worker e2e: harness child cleanup failed')); } await Promise.allSettled(lateAcquisitions); await Promise.allSettled(drains); cleanupErrors.push(...lateCleanupErrors, ...drainErrors); try { await seams.assertPortClosed(); states.push('port-closed'); } catch { cleanupErrors.push(new Error('c1-a worker e2e: port closure failed')); } for (const file of authored) if (hashes.has(file)) try { if (seams.hash(file) !== hashes.get(file)) throw new Error(); } catch { cleanupErrors.push(new Error(`c1-a worker e2e: authored input changed: ${path.basename(file)}`)); } if (ownsOutputs) try { seams.removeOwned(paths); states.push('outputs-removed'); } catch { cleanupErrors.push(new Error('c1-a worker e2e: output cleanup failed')); } unsubscribe(); if (!primary && aborted) primary = new Error(`c1-a worker e2e: aborted (${aborted})`); if (primary && cleanupErrors.length) throw new AggregateError([primary, ...cleanupErrors], 'c1-a worker e2e: failed'); if (primary) throw primary; if (cleanupErrors.length) throw new AggregateError(cleanupErrors, 'c1-a worker e2e: cleanup failed'); }
  return states;
}

async function runInternalHarness(root: string): Promise<void> { assertInternalHarnessInvocation(process.argv.slice(2), process.env, process.versions.node); installCloudflareProcessBoundary(root); let guard: EgressGuard | undefined; let harness: Harness | undefined; let bridge: { close(): Promise<void> } | undefined; const lifecycle = createInternalHarnessLifecycle(); const terminate = () => lifecycle.terminate(); process.once('SIGTERM', terminate); process.once('SIGINT', terminate); try { if (lifecycle.signal.aborted) fail('bridge root smoke'); guard = await startEgressGuard(); const { createTestHarness } = await import('wrangler'); harness = createTestHarness({ workers: [{ configPath: './wrangler.jsonc', vars: C1_A_HARNESS_VARS }] }) as unknown as Harness; await harness.listen(); await runOutboundCanary(harness, guard); bridge = await startBridge(harness); await emitReadyAfterBridgeSmoke((signal) => assertBridgeRootSmoke(fetch, signal), () => process.stdout.write(`${C1_A_WORKER_E2E_READY}\n`), lifecycle.signal); await lifecycle.stopped; } finally { process.removeListener('SIGTERM', terminate); process.removeListener('SIGINT', terminate); if (bridge) await bridge.close(); if (harness) await harness.close(); if (guard) guard.close(); } }

if (import.meta.main) { const root = path.resolve(MODULE_DIR, '..'); const internal = process.argv.slice(2).includes(INTERNAL_MODE); try { if (internal) await runInternalHarness(root); else await runC1AWorkerE2E(process.argv.slice(2), root); } catch { process.stderr.write(internal ? 'c1-a worker e2e: internal failed\n' : 'c1-a worker e2e: failed\n'); process.exitCode = 1; } }
