import { OAuthProvider } from '@cloudflare/workers-oauth-provider';
import { createMcpHandler } from 'agents/mcp';

import { authHandler, type Env } from './authHandler';
import { createEventEveryMcpServer } from './tools';

/**
 * The Event Every MCP Worker.
 *
 * A SEPARATE Worker from the app, and not by preference. The app's entry point
 * is generated by OpenNext, which owns the default export that OAuthProvider
 * needs here, so the two cannot share one. Keeping them apart also means a bad
 * MCP deploy can never take eventevery.com down.
 *
 * It holds no database binding and no encryption key. Every read and write goes
 * back through the app's own API carrying a signed actor token, so saving an
 * event over MCP runs the same envelope encryption, the same account scoping
 * and the same tombstones as saving one in a browser.
 */
const apiHandler = {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    // Built per request so each closes over its own env. A Workers isolate
    // serves overlapping requests, so a module-scoped handler here would be a
    // real concurrency bug rather than a style preference.
    const self = new URL(request.url).hostname;
    const handler = createMcpHandler(() => createEventEveryMcpServer(env), {
      route: '/mcp',
      // Browser-based clients send an Origin and are refused before the
      // JSON-RPC layer if it is not listed. Without claude.ai here the failure
      // is silent and baffling: the CORS preflight passes, a CLI client works,
      // and only the browser handshake dies with nothing useful shown.
      allowedOriginHostnames: ['claude.ai', 'www.claude.ai', self, 'localhost', '127.0.0.1'],
    });
    return handler(request, env, ctx);
  },
};

/**
 * Named rather than exported anonymously, so a stack trace and the lint rule
 * both have something to point at.
 */
const provider = new OAuthProvider({
  apiRoute: '/mcp',
  apiHandler,
  defaultHandler: authHandler,
  authorizeEndpoint: '/authorize',
  tokenEndpoint: '/token',
  clientRegistrationEndpoint: '/register',
  scopesSupported: ['account'],
});

export default provider;
